name: C++ CI

on:
  pull_request:
  push:

jobs:
  heap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install compiler
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Build heap
        run: |
          g++ -std=c++17 heap_hw/main.cpp -o heap

      - name: Run heap
        run: ./heap

